### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [Arcticons-Team/Arcticons#3118]
[com.donnnno.arcticons.daynight_1490.html](https://github.com/user-attachments/files/23872500/com.donnnno.arcticons.daynight_1490.html)

Could you please clean the cache and rebuild the apk? Thanks!

**Comment by Donnnno** [comment]
Sure! Just gotta find out how 🙃

**Comment by linsui** [comment]
Still same diff. Maybe caused by jdk version difference?

**Comment by Donnnno** [comment]
@Kaiserdragon2 do you know if it's possible to overwrite the current APKs at the latest release without deleting the release altogether?

https://github.com/Arcticons-Team/Arcticons/actions/runs/19825539107/job/56965992589

<img width="445" height="64" alt="Image" src="https://github.com/user-attachments/assets/6850d3e6-557d-4e31-9b4f-297bc7cee2b3" />

**Comment by Kaiserdragon2** [comment]
> [@Kaiserdragon2](https://github.com/Kaiserdragon2) do you know if it's possible to overwrite the current APKs at the latest release without deleting the release altogether?
> 
> https://github.com/Arcticons-Team/Arcticons/actions/runs/19825539107/job/56965992589
> <img alt="Image" width="445" height="64" src="https://private-user-images.githubusercontent.com/31142286/521867584-6850d3e6-557d-4e31-9b4f-297bc7cee2b3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3NzAwNTMsIm5iZiI6MTc2NDc2OTc1MywicGF0aCI6Ii8zMTE0MjI4Ni81MjE4Njc1ODQtNjg1MGQzZTYtNTU3ZC00ZTMxLTliNGYtMjk3YmM3Y2VlMmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjAzVDEzNDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMGFhODJiYmU5OWMzOGFjNmEyZTIyMmIzODg2ODY5ZThhYzQ0ZjkxOGE2NjdjOTlhYzg4MjQ3M2I2N2IxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z7sbDcJPGsT-vu2B4mNNXywRJa5S3gD6L14m8zKq-BA">

The only way would be to build it locally and replace the apk by editing the release. But by the looks of it you already tried this approach.

**Comment by Donnnno** [comment]
I tried to run the action after removing the APKs, but that didn't work, so I uploaded them back after. I can try doing a local build tho!

**Comment by Donnnno** [comment]
Ahhh, I think I understand it: the tag was created too early:

<img width="1305" height="189" alt="Image" src="https://github.com/user-attachments/assets/bb060750-bc55-4991-99f3-b2d1113e4d6a" />

<img width="514" height="109" alt="Image" src="https://github.com/user-attachments/assets/efb46922-51f9-42cb-b418-7b02ad4165da" />

**Comment by Kaiserdragon2** [comment]
F-droid doesn't seem to pick up the new release.

**Comment by licaon-kter** [comment]
Were they fixed? This is still open

**Comment by Kaiserdragon2** [comment]
The Last Release used the same version Code as the one before that was fixed with the new Realese.

**Comment by linsui** [comment]
Still not reproducible. 

[com.donnnno.arcticons.you_1500.html](https://github.com/user-attachments/files/24392102/com.donnnno.arcticons.you_1500.html) Maybe the cache needs to be cleared before rebuild.

**Comment by Kaiserdragon2** [comment]
We build it in ci.
I tried building it locally and check it against the released ones with the rbhelper tools and always get rb confirmed I am not sure what causes this.

**Comment by linsui** [comment]
Is [this](https://github.com/Arcticons-Team/Arcticons/blob/14.0.0/.github/workflows/BuildRelease.yml) the CI config used to build the release apks? It uses Zulu 21 while we use openjdk 17. This will cause difference of cause so I tried openjdk 21. But now there are more differences. Any idea? We can't use Zulu so can you switch to openjdk, i.e. temurin?

**Comment by Kaiserdragon2** [comment]
Yes it is.
When i searched for a solution i had the same idea so i tried to build it locally with temurin 17.
This was still RB.
I will update the CI too use Temurin nonetheless to be on the safe side.

**Comment by linsui** [comment]
So you get the same result with Zulu 21 and Temurin 17? Since you changed the CI to Temurin 21, I thought we should also use openjdk 21. And the apk is built from e35ba91b9dd016c9ba7d4140ad9a9ef57abe6b9d right

**Comment by linsui** [comment]
The problem was caused by a patch. Not sure why it's not needed anymore and why it causes problem but looks like it works after removing the patch. :) Thanks!

**Comment by Donnnno** [comment]
Great to hear that, thanks both of you! :)
